# Generated by Django 5.1.1 on 2024-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
