# Generated by Django 5.1.1 on 2024-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chatmessage_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_series',
            field=models.CharField(max_length=2),
        ),
    ]
